name: Test Get PR Comments Action

on:
  issue_comment:
  pull_request_review_comment:

jobs:
  get-pr-comments:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Get PR comments
        id: get_comments_step
        uses: boushi-bird/gh-actions-sandbox@v1.0.2
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          include-issue-comments: 'true'
